name: NegativeStain
atlas:
  acquisition:
      - setAtlasOptics
      - setAperturesForLowMag
      - resetStage
      - removeSlit
      # - eucentricSearch
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  acquisition:
    - setAperturesForLowMag
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricSearch
    - square
  targets:
    finders:
      - Regular pattern
    selectors:
      - Graylevel selector
mediumMag:
  acquisition:
    - setAperturesForHighMag
    - tiltToAngle
    - moveStage
    - mediumMagHole
    - autoFocus
    - waitDrift
highMag:
  acquisition:
    - highMag
