# Generated by Django 3.1.7 on 2021-09-13 14:38

import Smartscope.server.models.session
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasModel',
            fields=[
                ('atlas_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pixel_size', models.FloatField(null=True)),
                ('binning_factor', models.FloatField(null=True)),
                ('shape_x', models.IntegerField(null=True)),
                ('shape_y', models.IntegerField(null=True)),
                ('stage_z', models.FloatField(null=True)),
                ('status', models.CharField(default=None, max_length=20, null=True)),
            ],
            bases=(models.Model, autoscreenViewer.models.session.ExtraPropertyMixin),
        ),
        migrations.CreateModel(
            name='AutoloaderGrid',
            fields=[
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('grid_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('hole_angle', models.FloatField(null=True)),
                ('mesh_angle', models.FloatField(null=True)),
                ('quality', models.CharField(default=None, max_length=10, null=True)),
                ('notes', models.CharField(default=None, max_length=10000, null=True)),
                ('status', models.CharField(default=None, max_length=10, null=True)),
                ('start_time', models.DateTimeField(default=None, null=True)),
                ('last_update', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detector_model', models.CharField(choices=[('K2', 'Gatan K2'), ('K3', 'Gatan K3'), ('Ceta', 'FEI Ceta')], max_length=4)),
                ('atlas_mag', models.IntegerField(default=210)),
                ('atlas_max_tiles_X', models.IntegerField(default=6)),
                ('atlas_max_tiles_Y', models.IntegerField(default=6)),
                ('spot_size', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GridCollectionParams',
            fields=[
                ('params_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('atlas_x', models.IntegerField(default=3)),
                ('atlas_y', models.IntegerField(default=3)),
                ('squares_num', models.IntegerField(default=3)),
                ('holes_per_square', models.IntegerField(default=3)),
                ('bis_max_distance', models.FloatField(default=0)),
                ('min_bis_group_size', models.IntegerField(default=1)),
                ('target_defocus_min', models.FloatField(default=-3)),
                ('target_defocus_max', models.FloatField(default=-3)),
                ('step_defocus', models.FloatField(default=0)),
                ('drift_crit', models.FloatField(default=-1)),
                ('tilt_angle', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HoleType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hole_size', models.FloatField(blank=True, default=None, null=True)),
                ('hole_spacing', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeshMaterial',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MeshSize',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('square_size', models.IntegerField()),
                ('bar_width', models.IntegerField()),
                ('pitch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('voltage', models.IntegerField(default=200)),
                ('spherical_abberation', models.FloatField(default=2.7)),
                ('microscope_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SquareModel',
            fields=[
                ('square_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('pixel_size', models.FloatField(null=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('unbinned_x', models.IntegerField(null=True)),
                ('unbinned_y', models.IntegerField(null=True)),
                ('binning_factor', models.FloatField(null=True)),
                ('shape_x', models.IntegerField(null=True)),
                ('shape_y', models.IntegerField(null=True)),
                ('stage_x', models.FloatField()),
                ('stage_y', models.FloatField()),
                ('stage_z', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('quality', models.CharField(max_length=20)),
                ('selected', models.BooleanField(default=False)),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('atlas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.atlasmodel')),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid')),
            ],
            options={
                'unique_together': {('name', 'atlas_id')},
            },
            bases=(models.Model, autoscreenViewer.models.session.ExtraPropertyMixin),
            managers=[
                ('withholes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('session', models.CharField(max_length=30)),
                ('date', models.CharField(editable=False, max_length=8)),
                ('version', models.CharField(editable=False, max_length=8)),
                ('working_dir', models.CharField(editable=False, max_length=300)),
                ('session_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('detector_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.detector')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', to_field='name')),
                ('microscope_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.microscope')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(max_length=10)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.screeningsession')),
            ],
        ),
        migrations.CreateModel(
            name='HoleModel',
            fields=[
                ('hole_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pixel_size', models.FloatField(null=True)),
                ('dist_from_center', models.FloatField(null=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('unbinned_x', models.IntegerField()),
                ('unbinned_y', models.IntegerField()),
                ('binning_factor', models.FloatField(null=True)),
                ('shape_x', models.IntegerField(null=True)),
                ('shape_y', models.IntegerField(null=True)),
                ('stage_x', models.FloatField()),
                ('stage_y', models.FloatField()),
                ('area', models.FloatField()),
                ('quality', models.CharField(choices=[('0', 'Great'), ('1', 'Decent'), ('2', 'Contamination, Aggregate'), ('3',
                 'No particles, Empty hole'), ('4', 'Bad, crystalinne, thick ice'), ('5', 'Cracked')], max_length=20, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('bis_group', models.CharField(max_length=30, null=True)),
                ('bis_type', models.CharField(max_length=30, null=True)),
                ('class_num', models.IntegerField(choices=[(0, 'Best'), (1, 'Medium'), (2, 'Worse')], default=None, null=True)),
                ('completion_time', models.DateTimeField(null=True)),
                ('manual_addition', models.BooleanField(default=False)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid')),
                ('square_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.squaremodel')),
            ],
            options={
                'unique_together': {('name', 'square_id')},
            },
            bases=(models.Model, autoscreenViewer.models.session.ExtraPropertyMixin),
        ),
        migrations.CreateModel(
            name='HighMagModel',
            fields=[
                ('hm_id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pixel_size', models.FloatField(null=True)),
                ('status', models.CharField(default=None, max_length=20, null=True)),
                ('is_x', models.FloatField(null=True)),
                ('is_y', models.FloatField(null=True)),
                ('frames', models.CharField(default=None, max_length=120, null=True)),
                ('defocus', models.FloatField(null=True)),
                ('astig', models.FloatField(null=True)),
                ('angast', models.FloatField(null=True)),
                ('ctffit', models.FloatField(null=True)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid')),
                ('hole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.holemodel')),
            ],
            bases=(models.Model, autoscreenViewer.models.session.ExtraPropertyMixin),
        ),
        migrations.CreateModel(
            name='Finder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.CharField(choices=[('FFT finder', 'FFT finder'), ('Binary finder', 'Binary finder'), ('Regular Pattern', 'Regular Pattern'), (
                    'Square finder', 'Square finder'), ('AI Square finder', 'AI Square finder'), ('AI Hole finder', 'AI Hole finder')], max_length=100)),
                ('priority', models.PositiveIntegerField()),
                ('args', models.CharField(max_length=500)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid')),
            ],
        ),
        migrations.AddField(
            model_name='detector',
            name='microscope_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.microscope'),
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=60)),
                ('line_id', models.CharField(max_length=30)),
                ('column_name', models.CharField(max_length=20)),
                ('initial_value', models.BinaryField()),
                ('new_value', models.BinaryField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='holeType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.holetype'),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='meshMaterial',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.meshmaterial'),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='meshSize',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.meshsize'),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='params_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoscreenViewer.gridcollectionparams'),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.screeningsession'),
        ),
        migrations.AddField(
            model_name='atlasmodel',
            name='grid_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoscreenViewer.autoloadergrid'),
        ),
        migrations.AlterUniqueTogether(
            name='autoloadergrid',
            unique_together={('position', 'name', 'session_id')},
        ),
        migrations.AlterUniqueTogether(
            name='atlasmodel',
            unique_together={('grid_id', 'name')},
        ),
    ]
