# Generated by Django 3.1.7 on 2021-06-16 18:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='squaremodel',
            managers=[
                ('withholes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='astig',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='ctffit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='defocus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='finder',
            name='finder',
            field=models.CharField(choices=[('FFT finder', 'FFT finder'), ('Binary finder', 'Binary finder'), ('Regular Pattern', 'Regular Pattern'), ('Square finder', 'Square finder'), ('AI Square finder', 'AI Square finder'), ('AI Hole finder', 'AI Hole finder')], max_length=100),
        ),
    ]
