# Generated by Django 3.1.7 on 2021-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0002_auto_20210616_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holemodel',
            name='quality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
