# Generated by Django 3.1.7 on 2021-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0003_auto_20210618_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='holemodel',
            name='manual_label',
            field=models.BooleanField(default=False),
        ),
    ]
