# Generated by Django 3.1.7 on 2021-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0004_holemodel_manual_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holemodel',
            name='manual_label',
        ),
        migrations.AlterField(
            model_name='holemodel',
            name='quality',
            field=models.CharField(choices=[('0', 'Great'), ('1', 'Decent'), ('2', 'Contamination, Aggregate, Crack'), ('3', 'No ice / Empty hole'), ('4', 'Bad, crystalinne, thick ice'), ('5', 'No particles')], max_length=20, null=True),
        ),
    ]
