# Generated by Django 3.1.7 on 2021-07-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0005_auto_20210702_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='highmagmodel',
            name='angast',
            field=models.FloatField(null=True),
        ),
    ]
