# Generated by Django 3.1.7 on 2021-07-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0006_highmagmodel_angast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holemodel',
            name='class_num',
            field=models.IntegerField(choices=[(0, 'Best'), (1, 'Medium'), (2, 'Worse')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='holemodel',
            name='quality',
            field=models.CharField(choices=[('0', 'Great'), ('1', 'Decent'), ('2', 'Contamination, Aggregate'), ('3', 'No particles, Empty hole'), ('4', 'Bad, crystalinne, thick ice'), ('5', 'Cracked')], max_length=20, null=True),
        ),
    ]
