# Generated by Django 3.1.7 on 2021-08-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0007_auto_20210712_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='tilt_angle',
            field=models.FloatField(default=0),
        ),
    ]
