# Generated by Django 3.1.7 on 2021-08-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoscreenViewer', '0008_gridcollectionparams_tilt_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoloadergrid',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='holemodel',
            name='completion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='holemodel',
            name='manual_addition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autoloadergrid',
            name='last_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
