# Generated by Django 3.1.7 on 2022-06-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microscope',
            name='loader_size',
            field=models.IntegerField(default=12),
        ),
    ]
