# Generated by Django 3.1.7 on 2022-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microscope',
            name='scope_path',
            field=models.CharField(default='/mnt/scope', max_length=200),
        ),
    ]
