# Generated by Django 3.1.7 on 2022-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_microscope_scope_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='c2_perc',
            field=models.FloatField(default=100),
        ),
    ]
