# Generated by Django 4.0.5 on 2022-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_holemodel_dist_from_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='offset_distance',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='gridcollectionparams',
            name='offset_targeting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='offset',
            field=models.FloatField(default=0),
        ),
    ]
