# Generated by Django 4.0.5 on 2022-08-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_v07_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='frames_directory',
            field=models.CharField(default='/mnt/scope/movies/', help_text='Location of the frames directory from the smartscope container. Should not need change for K2/K3 detectors.', max_length=200),
        ),
        migrations.AddField(
            model_name='detector',
            name='frames_windows_directory',
            field=models.CharField(default='movies', help_text='Location of the frames from the perspective of SerialEM. This values will use the SetDirectory command. Should not need change for K2/K3 setups.', max_length=200),
        ),
    ]
