# Generated by Django 4.0.5 on 2022-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_detector_frames_directory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='atlas_to_search_offset_x',
            field=models.FloatField(default=0, help_text='X stage offset between the atlas and Search mag. Similar to the Shift to Marker offset'),
        ),
        migrations.AddField(
            model_name='detector',
            name='atlas_to_search_offset_y',
            field=models.FloatField(default=0, help_text='Y stage offset between the atlas and Search mag. Similar to the Shift to Marker offset'),
        ),
        migrations.AddField(
            model_name='gridcollectionparams',
            name='force_process_from_average',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microscope',
            name='vendor',
            field=models.CharField(choices=[('TFS', 'TFS / FEI'), ('JEOL', 'JEOL')], default='TFS', max_length=30),
        ),
    ]
