# Generated by Django 4.0.5 on 2022-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_detector_atlas_to_search_offset_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highmagmodel',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='location',
            field=models.CharField(help_text='Name of the institute, departement or room for the microscope.', max_length=30),
        ),
        migrations.AlterField(
            model_name='microscope',
            name='name',
            field=models.CharField(help_text='Name of your microscope', max_length=100),
        ),
    ]
