# Generated by Django 4.0.5 on 2023-02-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_gridcollectionparams_multishot_per_hole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningsession',
            name='version',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
