# Generated by Django 4.0.5 on 2023-05-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_screeningsession_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='hardwaredark_delay',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='detector',
            name='frames_directory',
            field=models.CharField(default='/mnt/scope/movies/', help_text='Location of the frames directory from SmartScope that point to the same location as frames_windows_directory.', max_length=200),
        ),
        migrations.AlterField(
            model_name='detector',
            name='frames_windows_directory',
            field=models.CharField(default='movies', help_text='Location of the frames from the perspective of SerialEM. This values will use the SetDirectory command.', max_length=200),
        ),
    ]
