# Generated by Django 4.0.5 on 2023-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_gridcollectionparams_hardwaredark_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='afis',
            field=models.BooleanField(default=False),
        ),
    ]
