# Generated by Django 4.2.2 on 2023-08-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_gridcollectionparams_afis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holemodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='squaremodel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='gridcollectionparams',
            name='afis',
            field=models.BooleanField(default=False, verbose_name='AFIS'),
        ),
        migrations.AlterField(
            model_name='gridcollectionparams',
            name='hardwaredark_delay',
            field=models.IntegerField(default=-1, verbose_name='Hardware Dark Delay'),
        ),
    ]
