# Generated by Django 4.2.2 on 2023-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_holemodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='atlas_c2_aperture',
            field=models.IntegerField(default=70, help_text='Size of the aperture in microns to use during the atlas procedure. Only works on TFS scopes'),
        ),
        migrations.AddField(
            model_name='gridcollectionparams',
            name='coldfegflash_delay',
            field=models.IntegerField(default=-1, help_text='Number of hours between cold FEG flashes. Will only work if the microscope has a cold FEG. Values smaller than 0 will disable the procedure.', verbose_name='Cold Feg Flash Delay'),
        ),
        migrations.AddField(
            model_name='microscope',
            name='aperture_control',
            field=models.BooleanField(default=False, help_text='Check box if serialEM is able to control the aperture selection. Check only if you have JEOL CRYOARM, or a TFS autoloader system.'),
        ),
        migrations.AddField(
            model_name='microscope',
            name='cold_FEG',
            field=models.BooleanField(default=False, help_text='Check if the microscope has a cold FEG to enable the flashing operations. Only works on CRYOARM at the moment.'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_to_search_offset_x',
            field=models.FloatField(default=0, help_text='X stage offset between the atlas and Search mag. Similar to the Shift to Marker offset. Does not do anything at this time.'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_to_search_offset_y',
            field=models.FloatField(default=0, help_text='Y stage offset between the atlas and Search mag. Similar to the Shift to Marker offset. Does not do anything at this time.'),
        ),
    ]
