# Generated by Django 4.2.2 on 2023-10-20 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0015_detector_atlas_c2_aperture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='gridcollectionparams',
            name='coldfegflash_delay',
            field=models.IntegerField(default=-1, help_text='Number of hours between cold FEG flashes. Will only work if the microscope has a cold FEG. Values smaller than 0 will disable the procedure.', verbose_name='ColdFEG Flash Delay'),
        ),
        migrations.CreateModel(
            name='CustomUserPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(editable=False, max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'customuserpath',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomGroupPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(editable=False, max_length=300)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', to_field='name')),
            ],
            options={
                'db_table': 'customgrouppath',
                'abstract': False,
            },
        ),
    ]
