# Generated by Django 4.2.2 on 2023-10-20 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('API', '0016_screeningsession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgrouppath',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', to_field='name'),
        ),
        migrations.AlterField(
            model_name='customgrouppath',
            name='path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customuserpath',
            name='path',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='customuserpath',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
