# Generated by Django 4.2.2 on 2024-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_classifier_created_at_finder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highmagmodel',
            name='ice_thickness',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='tilt_angle',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='highmagmodel',
            name='tilt_axis_angle',
            field=models.FloatField(null=True),
        ),
    ]
