# Generated by Django 4.2.2 on 2024-07-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0019_highmagmodel_ice_thickness_highmagmodel_tilt_angle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTypeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_c2_aperture',
            field=models.IntegerField(default=70, help_text='Size of the aperture in microns to use during the atlas procedure. Only works on TFS scopes at this time.'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_to_search_offset_x',
            field=models.FloatField(default=0, help_text='X stage offset between the atlas and Search mag. Similar to the Shift to Marker offset.'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_to_search_offset_y',
            field=models.FloatField(default=0, help_text='Y stage offset between the atlas and Search mag. Similar to the Shift to Marker offset.'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='frames_windows_directory',
            field=models.CharField(blank=True, default='movies', help_text='Location of the frames from the perspective of SerialEM. This values will use the SetDirectory command. Leave this field empty for Falcon detectors.', max_length=200),
        ),
        migrations.CreateModel(
            name='TagGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('grid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.autoloadergrid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SampleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
