# Generated by Django 4.2.2 on 2024-07-16 15:42

from django.db import migrations

def create_models(apps, schema_editor):
    SampleTypeTag = apps.get_model('API', 'SampleTypeTag')

    # Create instances of the models
    SampleTypeTag.objects.create(name="Virion")
    SampleTypeTag.objects.create(name="Filament")
    SampleTypeTag.objects.create(name="Cell")
    SampleTypeTag.objects.create(name="Bacteria")
    SampleTypeTag.objects.create(name="Liposome")
    SampleTypeTag.objects.create(name="Single Particle", description="Purified sample for single particle analysis.")
    SampleTypeTag.objects.create(name="Tomography", description="Sample for tomography.")


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_sampletypetag_alter_detector_atlas_c2_aperture_and_more'),
    ]

    operations = [
        migrations.RunPython(create_models)
    ]
