# Generated by Django 4.2.2 on 2024-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_create_sampletype_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='highmag_aperture_size',
            field=models.IntegerField(default=50, help_text='Size of the aperture for the View and Record presets.', verbose_name='High Mag Aperture Size'),
        ),
        migrations.AddField(
            model_name='gridcollectionparams',
            name='objective_aperture_size',
            field=models.IntegerField(default=0, help_text='Objective aperture to use for View and Record. 0 means no aperture.', verbose_name='Objective Aperture Size'),
        ),
    ]
