# Generated by Django 4.2.2 on 2024-09-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_gridcollectionparams_highmag_aperture_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridcollectionparams',
            name='beam_centering_delay',
            field=models.IntegerField(default=-1, help_text='Number of minutes between beam centering procedures. Values smaller than 0 will disable the procedure.', verbose_name='Beam Centering Delay'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='atlas_c2_aperture',
            field=models.IntegerField(default=70, help_text='Size of the aperture in microns to use during the atlas procedure. Should be set to 0 on JEOL to remove the aperture.'),
        ),
    ]
