FROM nvidia/cuda:12.1.0-base-ubuntu18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	python3-dev default-libmysqlclient-dev build-essential wget libglib2.0-0 ffmpeg libsm6 libxext6 curl mariadb-server && \
	apt-get clean && rm -rf /var/cache/apt/lists

RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
	bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3 && \
	rm Miniconda3-latest-Linux-x86_64.sh

RUN wget https://bio3d.colorado.edu/imod/AMD64-RHEL5/imod_4.11.24_RHEL7-64_CUDA10.1.sh && ls && \
	yes | bash imod_4.11.24_RHEL7-64_CUDA10.1.sh -name IMOD && \
	rm imod_4.11.24_RHEL7-64_CUDA10.1.sh

ADD config/singularity/ctffind /usr/local/

ADD config/docker/requirements.txt .

ENV PATH=$PATH:/opt/smartscope/Smartscope/bin:/opt/miniconda3/bin:$IMOD_DIR/bin

RUN conda update -y conda && \
	yes | conda install python=3.9 cudatoolkit=10.2 cudnn=7.6 git && \
	yes | pip install numpy==1.21.0 && \
	yes | pip install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cu102 && \
	yes | pip install -r requirements.txt && \
	yes | pip install ipython && \
	conda clean --all

# create a non-root user
ARG USER_ID=9999

RUN	useradd -m --no-log-init --system  --uid $USER_ID smartscope_user